image:
  repository: 127214174194.dkr.ecr.eu-central-1.amazonaws.com/django_app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

autoscaler:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "myapp-db.czug8wokie9j.eu-central-1.rds.amazonaws.com"
  POSTGRES_USER: postgres
  POSTGRES_DB: myapp
  POSTGRES_PASSWORD: admin123AWS23
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: "your-secret-key-here-change-in-production"

# Bitnami PostgreSQL configuration (disabled - using RDS)
postgresql:
  enabled: false

