{{- range .Values.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-repo
  namespace: {{ $.Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: {{ .url }}
  {{- if .username }}
  username: {{ .username }}
  {{- end }}
  {{- if .password }}
  password: {{ .password }}
  {{- end }}
  type: git
{{- end }}